---
title: "n-sink rasterization: process outline"
author: "Jeffrey Hollister"
date: "2018-08-10"
output:
  xaringan::moon_reader:
    css: ["default", "custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

---
class: center, middle

# Acquire 

---
# Acquire: NHD+ 12-digit HUCs

- Source file
  - NHDPlusV21_NE_01_WBDSnapshot_03.7z
- Source data
  - Shapefile
  - NHDPlusNE/NHDPlus01/WBDSnapshot/WBD/WBD_Subwatershed
  
---
# Acquire: NHD+ Flowlines

- Source file
  - NHDPlusV21_NE_01_NHDSnapshot_04.7z
- Source data
  - Shapefile
  - NHDPlusNE/NHDPlus01/NHDSnapshot/Hydrography/NHDFlowline

---
# Acquire: NHD+ Waterbodies

- Source file
  - NHDPlusV21_NE_01_NHDSnapshot_04.7z
- Source data
  - Shapefile
  - NHDPlusNE/NHDPlus01/NHDSnapshot/Hydrography/NHDWaterbody
  
---
# Acquire: NHD+ Flow Direction

- Source file
  - NHDPlusV21_NE_01_01a_FdrFac_01.7z
- Source data
  - ESRI Raster
  - NHDPlusNE/NHDPlus01/NHDPlusFdrFac01a/fdr
  
---
# Acquire: NHD+ Data Tables

- Source files
  - NHDPlusV21_NE_01_NHDPlusAttributes_08.7z
  - NHDPlusV21_NE_01_EROMExtension_05.7z
- Source Data
  - dbf
  - Time of Travel (TOTMA): NHDPlusNE/NHDPlus01/NHDPlusAttributes/PlusFlowlineVAA.dbf
  - Discharge (Q0001E): NHDPlusNE/NHDPlus01/EROMExtension/EROM_MA0001.DBF 
---
# Acquire: SSURGO

---
# Acquire: Impervious Surface

---
# Acquire: Miscellany

- approximate download time
- what is needed to download
- provides all data for all of NE
- cache data locally 

---
class: center, middle

# Clean

---

#Clean: Specific HUC

---

#Clean: Raster Conformity

---
class: center, middle

# Create 

---
# Create: removal raster
- Land removal
- Lake removal
- Stream removal

- notes: generate at 10m, filter, re-scale to 30m
  - need explanation/example as to why this is good...

---
# Create: type raster
- start with removal rasters and convert positive removal values to a type

---
# Create: Combine removal and type
- raster stack

---
# Create: Flowpath 
- 

---
class: center, middle

# Summarize 

---
# Summarize: Extract 

---
# Summarize: Clean

---
# Summarize: Report

---
class: center, middle

# Now what?

---
# Now what?: Static Maps
- Which static maps to create?
- Brute force
- Something else?
  - Flow accumulation?

---
# Now what?: R Package
- Code for doing this is a hot-mess
- R package is obvious solution
- Facilitates use with other tools
  - e.g. ArcGIS R Bridge

---
# Now what?: Web UI
- Stay in R?
  - Shiny
- ArcGIS?
  - Would need to use R Bridge for Arc
    - <https://r-arcgis.github.io/>
  - Or...
  - Re-work some portion of the workflow
    - Flow path generation
    - Extracting
    - Summarizing
---
class: center, middle

# Thanks and Questions!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).